[package]
name = "dirtybase"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirtybase_orm = { path = "../../lib/dirtybase_orm" }
actix-web = "4.3.0"
anyhow = "1.0.68"
clap = { version = "4.1.4", features = ["derive"] }
dotenv = "0.15.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "mysql", "sqlite", "any", "chrono", "json"] }
async-trait = "0.1.64"
